export { readFile, writeFile, patchFile } from "./file";
export { spawnCli } from "./cli";
export type { SpawnOptions, SpawnResult } from "./cli";
export { getSystemDiagnostics } from "./sysinfo";
export type { SystemDiagnostics } from "./sysinfo";
export { grepSearch } from "./search";
export type { SearchMatch, SearchOptions } from "./search";
export { parse, encodeResult, PROTO_START, PROTO_CLOSE } from "./proto";
export type { ParsedBlock } from "./proto";
export { getAvailableTools, toRegistryGrid, toHeaderInstruction, buildToolCallPayload, buildHeader, RETURN_GRID, RETURN_ASK, HITLActions, HITLGates, getHITLTools } from "./tool-registry";
export type { ToolDef, ToolParam } from "./tool-registry";
